# SITE CONFIGURATION
title: AnswersCo # your site title
description: > # Meta description of Homepage
  AnswersCo provides information on a variety of topics including history,
  science, and math aimed at helping students succeed.
baseurl: "" # the subpath of your site, e.g. /blog

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'All Pages', link: '/all-pages'}

tagline: >
  An online hub for information on various topics.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: "_pages"
    values:
      permalink: /:basename/

exclude: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
